PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS food;
DROP TABLE IF EXISTS animal;
DROP TABLE IF EXISTS animal_food;
DROP TABLE IF EXISTS owner;
DROP TABLE IF EXISTS pet;

CREATE TABLE food (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE animal (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE animal_food (
  animal_id INTEGER UNIQUE NOT NULL,
  food_id INTEGER NOT NULL,

  PRIMARY KEY(animal_id, food_id),

  FOREIGN KEY (animal_id) REFERENCES animal(id)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  FOREIGN KEY (food_id) REFERENCES food(id)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE owner (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  UNIQUE(first_name, last_name)
);

CREATE TABLE pet (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id INTEGER NOT NULL,
  animal_id INTEGER NOT NULL,
  name TEXT NOT NULL,

  UNIQUE(owner_id, name)
  FOREIGN KEY (owner_id) REFERENCES owner(id)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  FOREIGN KEY (animal_id) REFERENCES animal(id)
    ON DELETE CASCADE ON UPDATE NO ACTION
);
